name: digichecks-shacl-service

services:
  api:
    container_name: api-digichecks-shacl-service
    build: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FERNET_KEY=${FERNET_KEY}
      - SSL_MODE=disable
    depends_on:
      - db
    restart: always
  db:
    container_name: db-digichecks-shacl-service
    image: postgres:17-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always

volumes:
  postgres_data:
